[master]
master ansible_host=192.168.56.10 ansible_ssh_private_key_file=.vagrant/machines/master/virtualbox/private_key

[datanodes]

datanode1 ansible_host=192.168.56.12 ansible_ssh_private_key_file=.vagrant/machines/datanode1/virtualbox/private_key
datanode2 ansible_host=192.168.56.13 ansible_ssh_private_key_file=.vagrant/machines/datanode2/virtualbox/private_key

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'